# Generated by Django 3.0.8 on 2020-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='site_return',
            field=models.CharField(choices=[('5', 'Very Likely'), ('4', 'Likely'), ('3', 'Sometimes'), ('2', 'Not Likely'), ('1', 'Never')], max_length=1),
        ),
    ]
